//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finansas.Buddie.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class AportacionesMeta
    {
        public int idAportacion { get; set; }
        public Nullable<int> idMeta { get; set; }
        public decimal monto { get; set; }
        public Nullable<System.DateTime> fechaAportacion { get; set; }
    
        public virtual MetasAhorro MetasAhorro { get; set; }
    }
}
