//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finansas.Buddie.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetasAhorro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetasAhorro()
        {
            this.AportacionesMeta = new HashSet<AportacionesMeta>();
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public int idMeta { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string nombreMeta { get; set; }
        public string descripcion { get; set; }
        public decimal montoObjetivo { get; set; }
        public Nullable<decimal> montoActual { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public Nullable<bool> estaCompletada { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AportacionesMeta> AportacionesMeta { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
