//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finansas.Buddie.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int idToken { get; set; }
        public string Token1 { get; set; }
        public System.DateTime Fecha { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
